In [1]:
%matplotlib inline
from __future__ import division

import pandas as pd
import utils

In [2]:
visitors, events, devices, url_categories = utils.load_data()

/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2821: DtypeWarning: Columns (5,6,7,8,11,12,13,14,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):
/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2821: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [3]:
categorized_events = utils.categorize_events(events, url_categories)

In [127]:
pharma_visits =pd.merge(pharma, good_events, on='url_root')

In [128]:
pharma_visits['authorized_visit'] = pharma_visits.identity_type.apply(lambda x: 1 if x=='AUT' else 0)

In [129]:
pharma_ratio = pharma_visits.groupby('url_root').authorized_visit.agg(['sum', 'count']).reset_index().rename(columns={'sum':'authorized_views', 'count':'total_views'})

In [130]:
from __future__ import division
pharma_ratio['pct_authorized'] = pharma_ratio.apply(lambda x: x['authorized_views']/x['total_views'], axis=1)

In [132]:
pharma = pd.merge(pharma, pharma_ratio[['url_root', 'pct_authorized', 'authorized_views', 'total_views']], on='url_root')

In [133]:
pharma['pharma_id'] = range(len(pharma))

In [135]:
p = pharma[['pharma_id', 'disease_category', 'disease', 'pct_authorized', 'authorized_views', 'total_views']]

In [136]:
t1 = pd.merge(p, p, on ='disease_category')

In [137]:
t1 = t1[t1.pharma_id_x!=t1.pharma_id_y]

In [144]:
t1.groupby('pharma_id_x')[['authorized_views_y', 'total_views_y']].agg(['sum', 'count'])

            authorized_views_y       total_views_y
                           sum count           sum count
pharma_id_x
0                          220     3           298     3
1                          220     3           298     3
2                        64479    33         93915    33
3                        64479    33         93915    33
4                       255570     7        335597     7
5                       255570     7        335597     7
6                        64775    33         94387    33
7                        64775    33         94387    33
8                        63353    33         92543    33
9                        63353    33         92543    33
10                       93538     8        123913     8
11                       93538     8        123913     8
12                       94476     8        125413     8
13                         692     1           912     1
14                         692     1           912     1
15                       64741    33         94327    33
16                       64741    33         94327    33
17                       83869     4        109815     4
18                       83869     4        109815     4
19                       94970     8        125995     8
20                       94970     8        125995     8
21                       64933    33         94537    33
22                       64933    33         94537    33
23                       95114     8        126261     8
24                       65051    33         94749    33
25                        1070     4          1486     4
26                        1070     4          1486     4
27                        1070     4          1486     4
28                       65023    33         94737    33
29                       65023    33         94737    33
...                        ...   ...           ...   ...
80                        3824     2          5224     2
81                      169744     9        222458     9
82                         449     4           627     4
83                        1251     4          1672     4
84                       85413     2        111983     2
85                       95066     8        126193     8
86                       90072     2        119167     2
87                       65090    33         94808    33
88                         863     3          1188     3
89                        2536     3          3518     3
90                       65091    33         94805    33
91                      168935     9        221365     9
92                       87390     8        115233     8
93                       57327    33         83721    33
94                       57327    33         83721    33
95                       57327    33         83721    33
96                        1368     1          1720     1
97                      169363     9        221961     9
98                       65086    33         94802    33
99                      257342     7        338106     7
100                       1245     4          1650     4
101                      65090    33         94808    33
102                      65054    33         94741    33
103                        968     4          1270     4
104                       1271     4          1693     4
105                      87742     2        115152     2
106                      64831    33         94455    33
107                      64782    33         94341    33
108                     169051     9        221566     9
109                     168477     9        220623     9

[106 rows x 4 columns]

In [145]:
pharma.sample()

,url,site_category,site_sub_category,disease_category,disease,url_root,pct_authorized,authorized_views,total_views,pharma_id
21,https://www.alecensa.com/hcp.html,Pharma,Branded HCP,Oncology,"anaplastic lymphoma kinase (ALK)-positive, met...",alecensa,0.580882,158,272,21

In [147]:
client_id = 21

In [149]:
pharma[pharma.pharma_id==21].pct_authorized

21    0.580882
Name: pct_authorized, dtype: float64

In [ ]:
def deep_dive()